// Generated by gencpp from file rosi_defy/RosiMovementArray.msg
// DO NOT EDIT!


#ifndef ROSI_DEFY_MESSAGE_ROSIMOVEMENTARRAY_H
#define ROSI_DEFY_MESSAGE_ROSIMOVEMENTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rosi_defy/RosiMovement.h>

namespace rosi_defy
{
template <class ContainerAllocator>
struct RosiMovementArray_
{
  typedef RosiMovementArray_<ContainerAllocator> Type;

  RosiMovementArray_()
    : header()
    , movement_array()  {
    }
  RosiMovementArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , movement_array(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::rosi_defy::RosiMovement_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rosi_defy::RosiMovement_<ContainerAllocator> >::other >  _movement_array_type;
  _movement_array_type movement_array;





  typedef boost::shared_ptr< ::rosi_defy::RosiMovementArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosi_defy::RosiMovementArray_<ContainerAllocator> const> ConstPtr;

}; // struct RosiMovementArray_

typedef ::rosi_defy::RosiMovementArray_<std::allocator<void> > RosiMovementArray;

typedef boost::shared_ptr< ::rosi_defy::RosiMovementArray > RosiMovementArrayPtr;
typedef boost::shared_ptr< ::rosi_defy::RosiMovementArray const> RosiMovementArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosi_defy::RosiMovementArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosi_defy::RosiMovementArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosi_defy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'rosi_defy': ['/home/rosichallenge/catkin_ws/src/rosi_defy/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosi_defy::RosiMovementArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosi_defy::RosiMovementArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosi_defy::RosiMovementArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosi_defy::RosiMovementArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosi_defy::RosiMovementArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosi_defy::RosiMovementArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosi_defy::RosiMovementArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a054d7e26f4857f061b21c11e4cd865f";
  }

  static const char* value(const ::rosi_defy::RosiMovementArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa054d7e26f4857f0ULL;
  static const uint64_t static_value2 = 0x61b21c11e4cd865fULL;
};

template<class ContainerAllocator>
struct DataType< ::rosi_defy::RosiMovementArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosi_defy/RosiMovementArray";
  }

  static const char* value(const ::rosi_defy::RosiMovementArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosi_defy::RosiMovementArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"RosiMovement[] movement_array\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rosi_defy/RosiMovement\n"
"int64 nodeID\n"
"float64 joint_var\n"
"\n"
;
  }

  static const char* value(const ::rosi_defy::RosiMovementArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosi_defy::RosiMovementArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.movement_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RosiMovementArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosi_defy::RosiMovementArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosi_defy::RosiMovementArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "movement_array[]" << std::endl;
    for (size_t i = 0; i < v.movement_array.size(); ++i)
    {
      s << indent << "  movement_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rosi_defy::RosiMovement_<ContainerAllocator> >::stream(s, indent + "    ", v.movement_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSI_DEFY_MESSAGE_ROSIMOVEMENTARRAY_H
